version: "3"

services:
  db:
    container_name: "postgres"
    image: postgres
    restart: always
    volumes:
      - "pgdata:/var/lib/postgresql/data"
      - "./server/sql:/docker-entrypoint-initdb.d"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "root"

  server:
    container_name: "server"
    restart: "always"
    build:
      context: "./"
      dockerfile: "./server/Dockerfile"
    environment:
      DB_URL: "postgres"
      DB_USERNAME: "root"
      DB_PASSWORD: "root"
      DB_NAME: "root"
      DB_PORT: "5432"
    ports:
      - "5000:80"
    depends_on:
      - db

volumes:
  pgdata:
